# Generated by Django 2.2.12 on 2020-12-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpload', '0002_auto_20201205_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='store',
            new_name='image',
        ),
    ]
